apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone1
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: udacity-devops-capstone-container
        image: kanikalimuthu/image_capstone_kk_new:latest
        ports:
        - containerPort: 80