apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone1
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 80
  type: LoadBalancer