apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: web